//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_suma_horas
    {
        public int Rut_trabajador { get; set; }
        public string Nombre_trabajador { get; set; }
        public string Apellido_trabajador { get; set; }
        public string Nombre_seccion { get; set; }
        public Nullable<int> Total_Horas { get; set; }
        public Nullable<System.DateTime> Mes { get; set; }
    }
}
